local_backend: true

backend:
  name: git-gateway
  repo: MattAndDev/netlilove
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/uploads

public_folder: /static/uploads

editor:
  preview: false

collections:
  - name: 'home'
    label: 'Home page'
    files:
      - file: static/content/home/home.md
        label: Home page
        name: home
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - label: 'Images'
            name: 'images'
            widget: 'list'
            summary: '{{fields.title}}'
            fields:
              - { label: 'Title', name: 'title', widget: string }
              - { label: 'Image', name: 'image', widget: image }
